//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HAM_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_prescription
    {
        public string id { get; set; }
        public string disease { get; set; }
        public string symptoms { get; set; }
        public string medicines { get; set; }
        public string ptu_medicines { get; set; }
        public string user_id { get; set; }
        public string dc_id { get; set; }
    
        public virtual tbl_doctor tbl_doctor { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
